
include ../Makefile.inc

ALL :
	echo Making Constants

#AtomicProperties.o : AtomicProperties.h AtomicProperties.cpp
	#$(CPP) $(PRJCPPFLAGS) -c AtomicProperties.cpp

#Constants.o : Constants.h Constants.cpp
	#$(CPP) $(PRJCPPFLAGS) -c Constants.cpp

clean :
	echo cleaning up in $(CURDIR)
	-@rm *.o 2>/dev/null || true
